# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170816_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_detail_street',
        ),
    ]
