# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170817_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_detail_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_type',
        ),
    ]
