# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170817_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_detail_postcode',
            field=models.CharField(default='BT66HJ', max_length=10, verbose_name='Zip/Postcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_instructions',
            field=models.TextField(blank=True, verbose_name='Special Requirements'),
        ),
    ]
