# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20171009_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='arriving',
        ),
        migrations.RemoveField(
            model_name='product',
            name='departing',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='arriving',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='departing',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='arriving',
            field=models.DateField(default='2017-09-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='departing',
            field=models.DateField(default='2017-09-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='arriving',
            field=models.DateField(default='2017-09-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='departing',
            field=models.DateField(default='2017-09-12'),
            preserve_default=False,
        ),
    ]
