# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_cartitem_departing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='arriving',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='departing',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
