# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20171025_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe customer id'),
        ),
    ]
